name = "KDTree3D32"
uuid = "c5f7c4d3-8c5e-6f5f-0e3f-34567890bcde"
version = "1.0.0"
authors = ["Murf <murf@parsetree.com>"]

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.6"
Random = "1"
Test = "1"
