# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "2fdcb26f494cdfd7707684df7155b106563f29e5"

[[deps.KDTree]]
path = "."
uuid = "a3f5a2b1-6a3c-4b3f-8c1d-123456789abc"
version = "1.0.0"
