# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "d08f7b4a13259cfd2e119cfe7db158aba78709b7"

[[deps.KDTree3D]]
path = "."
uuid = "c5f7c4d3-8c5e-6f5f-0e3f-34567890bcde"
version = "1.0.0"
