[package]
name = "kdtree-rust-64"
version = "1.0.0"
edition = "2021"
authors = ["Murf <murf@parsetree.com>"]
description = "A fast, memory-safe 64-bit coordinate KD-tree implementation"
repository = "https://github.com/WyoMurf/kdtree"
license = "LGPL-2.0"

[lib]
name = "kdtree64"
path = "src/lib.rs"
